[package] 
name = "is31fl3741"
version = "0.1.0"
edition = "2021"
authors = ["Liz Frost"]
categories = ["embedded", "no-std"]
description = "Driver for Lumissil Microsystem's IS31FL3741 IC"
license = "MIT"
repository = "https://github.com/stillinbeta/is31fl3741"
readme = "README.md"

[dependencies]
embedded-hal = "0.2.6"

[dev-dependencies]
cortex-m-rt = "0.6.10"
panic-halt = "0.2.0"
stm32g0xx-hal = {version = "0.1.3", features = ["rt", "stm32g071"]}

[features]
adafruit_rgb_13x9 = []

[[example]]
name = "stm32"
required-features = ["adafruit_rgb_13x9"]
