[package]
name = "ledmatrix"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
is31fl3741 = { path = "../../", features = ["framework_ledmatrix"] }
embedded-hal = "1.0"
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
fugit = "0.3.7"
rp2040-hal = { version = "0.11.0", features = ["rt", "critical-section-impl"] }
rp2040-panic-usb-boot = "0.6.0"
rp2040-boot2 = "0.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
