name: build

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            rust:
              - '**.rs'
              - 'Cargo.lock'
              - '.github/workflows/**'
      - if: steps.changes.outputs.rust == 'true'
        run: |
          cargo build --target=thumbv6m-none-eabi --all-features

          pushd examples/adafruit_rgb
          cargo build --target=thumbv6m-none-eabi --examples
          popd

          cargo install flip-link
          pushd examples/ledmatrix
          cargo build --examples
          popd

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            rust:
              - '**.rs'
              - 'Cargo.lock'
              - '.github/workflows/**'
      - if: steps.changes.outputs.rust == 'true'
        run: |
          cargo doc
          cargo fmt --all -- --check
          cargo clippy -- --deny=warnings
